# Prerequisites:
# $HEROKU_API_KEY (*) 	Heroku API key.
# $WAIT 	Wait until the Heroku deployment completes. Default: false.
# $DEBUG 	Turn on extra debug information. Default: false.
# For advanced cases, please, follow examples from the pipe's:
# README https://support.atlassian.com/bitbucket-cloud/docs/deploy-to-heroku/

image: clojure:openjdk-16-lein-slim-buster

# Workflow Configuration

pipelines:
  default:
    - parallel:
      - step:
          name: Build and Test
          caches:
            - maven
          script:
            - lein cljsbuild once optimized
  branches:
    master:
      - parallel:
        - step:
            name: Build and Test
            caches:
              - maven
            script:
              - lein uberjar
        - step:
            name: Archive code to send to Heroku
            script:
              - apt update -y
              - apt install -y git
              - git archive --format=tar.gz master -o showcase.tar.gz
            artifacts:
              - showcase.tar.gz
        - step:
            name: Security Scan
            script:
              # Run a security scan for sensitive data.
              # See more security tools at https://bitbucket.org/product/features/pipelines/integrations?&category=security
              - pipe: atlassian/git-secrets-scan:0.4.3
      - step:
          name: Deploy to Staging
          deployment: Staging
          clone:
            enabled: false
          script:
            - pipe: atlassian/heroku-deploy:1.2.1
              variables:
                HEROKU_API_KEY: $HEROKU_API_KEY
                HEROKU_APP_NAME: "robertm-staging"
                ZIP_FILE: showcase.tar.gz
                WAIT: "true"
                DEBUG: "false"
